#!/usr/bin/env bash
# 03-import-saved-objects.sh — import Kibana saved objects (dashboards, data views, connectors)
# from deploy/infrastructure/robot-saved-objects.ndjson.
#
# Uses POST /api/saved_objects/_import with overwrite=true so re-runs are safe.
#
# IMPORTANT: this imports the *structure* of connectors but NOT their secrets.
# After this runs, the 3 action connectors (Ollama Local, Ollama Vision, robot-arm)
# will exist but may need credentials re-entered via the Kibana UI or the
# /api/actions/connector/{id} endpoint with the missing secrets.

source "$(dirname "$0")/lib.sh"

NDJSON_FILE="$REPO_ROOT/deploy/infrastructure/robot-saved-objects.ndjson"
SRE_NDJSON="$REPO_ROOT/deploy/scripts/rebuild/saved-objects/sre-dashboard.ndjson"
COVERAGE_NDJSON="$REPO_ROOT/deploy/scripts/rebuild/saved-objects/training-coverage.ndjson"

if [[ ! -f "$NDJSON_FILE" ]]; then
  fail "Not found: $NDJSON_FILE"
fi

info "Importing $NDJSON_FILE into Kibana..."
resp=$(kb_post_f "api/saved_objects/_import?overwrite=true" "$NDJSON_FILE")
echo "$resp" | python3 -m json.tool

success=$(echo "$resp" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("success", False))')
count=$(echo "$resp" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("successCount", 0))')

if [[ "$success" == "True" ]]; then
  ok "Imported $count object(s)"
else
  warn "Import had errors — review output above"
fi

# Import SRE Dashboard (separate file)
if [[ -f "$SRE_NDJSON" ]]; then
  info "Importing SRE Dashboard from $SRE_NDJSON..."
  resp2=$(kb_post_f "api/saved_objects/_import?overwrite=true" "$SRE_NDJSON")
  echo "$resp2" | python3 -m json.tool
  sre_ok=$(echo "$resp2" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("success", False))')
  sre_count=$(echo "$resp2" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("successCount", 0))')
  if [[ "$sre_ok" == "True" ]]; then
    ok "Imported SRE Dashboard ($sre_count object(s))"
  else
    warn "SRE Dashboard import had errors — review output above"
  fi
else
  warn "SRE Dashboard not found at $SRE_NDJSON — skipping"
fi

# Import Training Coverage Map (separate file, generated by training-coverage-map.py)
if [[ -f "$COVERAGE_NDJSON" ]]; then
  info "Importing Training Coverage Map from $COVERAGE_NDJSON..."
  resp3=$(kb_post_f "api/saved_objects/_import?overwrite=true" "$COVERAGE_NDJSON")
  echo "$resp3" | python3 -m json.tool
  cov_ok=$(echo "$resp3" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("success", False))')
  cov_count=$(echo "$resp3" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("successCount", 0))')
  if [[ "$cov_ok" == "True" ]]; then
    ok "Imported Training Coverage Map ($cov_count object(s))"
  else
    warn "Training Coverage Map import had errors — review output above"
  fi
else
  warn "Training Coverage Map not found at $COVERAGE_NDJSON — run training-coverage-map.py first"
fi

echo
info "Verification — robot dashboards and data views:"
kb_get "api/saved_objects/_find?type=dashboard&per_page=1000" | python3 -c '
import json, sys
d = json.load(sys.stdin)
for o in d.get("saved_objects", []):
    title = o.get("attributes", {}).get("title", "")
    if any(p in title for p in ["Live Performance","Flywheel","Model Comparison","Training Observability","SRE Dashboard","Training Coverage"]):
        print(f"  dashboard: {title}")
'
kb_get "api/saved_objects/_find?type=index-pattern&per_page=1000" | python3 -c '
import json, sys
d = json.load(sys.stdin)
for o in d.get("saved_objects", []):
    title = o.get("attributes", {}).get("title", "")
    if "robot-" in title:
        print(f"  data view: {title}")
'

echo
warn "Action connectors need their secrets re-entered manually:"
warn "  Ollama Local  - URL to Ollama server, API key (if any)"
warn "  Ollama Vision - URL to Ollama server, API key (if any)"
warn "  robot-arm     - MCP URL: $MCP_URL"
