FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# LeRobot with feetech servo drivers
RUN pip3 install --ignore-installed zipp \
    "lerobot[feetech]"

COPY motor_node_v3.py /ros2_ws/motor_node.py

RUN echo '#!/bin/bash\nsource /opt/ros/humble/setup.bash\nexec "$@"' > /entrypoint.sh \
    && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["python3", "/ros2_ws/motor_node.py"]
